# Generated by Django 4.1.5 on 2023-01-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj',
            name='website',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
